#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const outPath = path.join(__dirname, '..', 'public', 'sitemap.xml');
const urlsFile = path.join(__dirname, 'urls.json');

const staticRoutes = [
  '/',
  '/landing',
  '/features',
  '/pricing',
  '/stores',
  '/products',
  '/search',
  '/wishlist',
  '/cart',
  '/checkout',
  '/confirmation',
  '/account'
];

function formatUrl(loc, opts = {}){
  const lastmod = opts.lastmod || new Date().toISOString().slice(0,10);
  const changefreq = opts.changefreq || 'weekly';
  const priority = (typeof opts.priority === 'number') ? opts.priority.toFixed(2) : '0.50';
  return `  <url>\n    <loc>https://libreshop.shop${loc}</loc>\n    <priority>${priority}</priority>\n    <changefreq>${changefreq}</changefreq>\n    <lastmod>${lastmod}</lastmod>\n  </url>`;
}

let dynamicUrls = [];

async function fetchFromSupabase() {
  const SUPABASE_URL = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL;
  const SUPABASE_KEY = process.env.SUPABASE_ANON_KEY || process.env.SUPABASE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  if (!SUPABASE_URL || !SUPABASE_KEY) return null;
  try {
    const productsRes = await fetch(`${SUPABASE_URL}/rest/v1/products?select=slug,id&is_active=eq.true`, {
      headers: {
        apikey: SUPABASE_KEY,
        Authorization: `Bearer ${SUPABASE_KEY}`
      }
    });
    if (!productsRes.ok) throw new Error(`Supabase products fetch failed: ${productsRes.status}`);
    const products = await productsRes.json();

    const storesRes = await fetch(`${SUPABASE_URL}/rest/v1/stores?select=slug,id&is_active=eq.true`, {
      headers: {
        apikey: SUPABASE_KEY,
        Authorization: `Bearer ${SUPABASE_KEY}`
      }
    });
    const stores = storesRes.ok ? await storesRes.json() : [];

    return { products, stores };
  } catch (e) {
    console.error('Supabase fetch failed:', e.message || e);
    return null;
  }
}

async function loadDynamicUrls() {
  // Priority: Supabase (if env vars provided) -> scripts/urls.json -> none
  const fromSupabase = await fetchFromSupabase();
  if (fromSupabase) {
    const out = [];
    (fromSupabase.products || []).forEach(p => {
      if (p && (p.slug || p.id)) out.push({ loc: `/product/${p.slug || p.id}`, opts: { priority: 0.85, changefreq: 'weekly', lastmod: null } });
    });
    (fromSupabase.stores || []).forEach(s => {
      if (s && (s.slug || s.id)) out.push({ loc: `/store/${s.slug || s.id}`, opts: { priority: 0.80, changefreq: 'weekly', lastmod: null } });
    });
    return out;
  }

  if (fs.existsSync(urlsFile)){
    try{
      const raw = fs.readFileSync(urlsFile,'utf8');
      const parsed = JSON.parse(raw);
      return parsed.map(u => (typeof u === 'string' ? { loc: u, opts: {} } : { loc: u.loc, opts: { priority: u.priority || 0.80, changefreq: u.changefreq || 'weekly', lastmod: u.lastmod } }));
    }catch(e){
      console.error('Erreur lecture urls.json :', e.message);
    }
  }
  return [];
}

const allUrls = [];
staticRoutes.forEach(r => allUrls.push({loc: r, opts: {priority: r==='/'?1.00:0.80, changefreq: r==='/'?'daily':'weekly'}}));
// load dynamic URLs (from Supabase or scripts/urls.json)
(async () => {
  const dyn = await loadDynamicUrls();
  dyn.forEach(u => allUrls.push({ loc: u.loc, opts: u.opts || {} }));

  const header = `<?xml version="1.0" encoding="UTF-8"?>\n<!-- sitemap generated by scripts/generate-sitemap.js -->\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n`;
  const footer = '\n</urlset>\n';

  const body = allUrls.map(u => formatUrl(u.loc, u.opts)).join('\n');
  const xml = header + body + footer;

  fs.writeFileSync(outPath, xml, 'utf8');
  console.log(`Sitemap généré : ${outPath} (${allUrls.length} URLs)`);
})();

