#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const outPath = path.join(__dirname, '..', 'public', 'sitemap.xml');
const urlsFile = path.join(__dirname, 'urls.json');

const staticRoutes = [
  '/',
  '/landing',
  '/features',
  '/pricing',
  '/stores',
  '/products',
  '/search',
  '/wishlist',
  '/cart',
  '/checkout',
  '/confirmation',
  '/account'
];

function formatUrl(loc, opts = {}){
  const lastmod = opts.lastmod || new Date().toISOString().slice(0,10);
  const changefreq = opts.changefreq || 'weekly';
  const priority = (typeof opts.priority === 'number') ? opts.priority.toFixed(2) : '0.50';
  return `  <url>\n    <loc>https://libreshop.shop${loc}</loc>\n    <priority>${priority}</priority>\n    <changefreq>${changefreq}</changefreq>\n    <lastmod>${lastmod}</lastmod>\n  </url>`;
}

let dynamicUrls = [];
if (fs.existsSync(urlsFile)){
  try{
    const raw = fs.readFileSync(urlsFile,'utf8');
    dynamicUrls = JSON.parse(raw);
  }catch(e){
    console.error('Erreur lecture urls.json :', e.message);
  }
}

const allUrls = [];
staticRoutes.forEach(r => allUrls.push({loc: r, opts: {priority: r==='/'?1.00:0.80, changefreq: r==='/'?'daily':'weekly'}}));
dynamicUrls.forEach(u => {
  // allow either string or object {loc,priority,changefreq,lastmod}
  if (typeof u === 'string') allUrls.push({loc: u, opts: {}});
  else if (u && u.loc) allUrls.push({loc: u.loc, opts: {priority: u.priority || 0.80, changefreq: u.changefreq || 'weekly', lastmod: u.lastmod}});
});

const header = `<?xml version="1.0" encoding="UTF-8"?>\n<!-- sitemap generated by scripts/generate-sitemap.js -->\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n`;
const footer = '\n</urlset>\n';

const body = allUrls.map(u => formatUrl(u.loc, u.opts)).join('\n');
const xml = header + body + footer;

fs.writeFileSync(outPath, xml, 'utf8');
console.log(`Sitemap généré : ${outPath} (${allUrls.length} URLs)`);

process.exit(0);
